apiVersion: v1
kind: Service
metadata:
  name: git-connectorsrv
  labels:
    app: git-connectorsrv
    service: git-connectorsrv
spec:
  ports:
   - port: 9082
     name: http
     targetPort: 8080
  selector:
    app: git-connector